name: Build wheels

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CIBW_BUILD: cp38-* cp39-* cp310-*
  CIBW_SKIP: "*-musllinux_*"
  CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
  CIBW_ARCHS: native
  CIBW_ARCHS_LINUX: "x86_64"
  CIBW_ARCHS_MACOS: "x86_64 arm64"
  CIBW_ARCHS_WINDOWS: "x86, AMD64"
  CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y"
  CIBW_BEFORE_BUILD: rustup show
  CIBW_BEFORE_BUILD_MACOS: "rustup target add aarch64-apple-darwin"
  # Upgrade numpy to make sure the binary is compatible with latest version
  # See https://github.com/numpy/numpy/issues/5888 for more info
  CIBW_BEFORE_TEST: python -m pip install pytest numpy --upgrade
  CIBW_TEST_COMMAND: python -m pytest {package}

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust
        run: |
          rustup update
          rustup component add cargo

      - name: Build wheels
        uses: joerick/cibuildwheel@v2.10.2

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
